USE spring_board;

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT AUTO_INCREMENT,
    password VARCHAR(20) NOT NULL,
    title VARCHAR(20) NOT NULL,
    contents VARCHAR(225) NOT NULL,
    likes INT NOT NULL DEFAULT 0,
    comments INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT user_PK PRIMARY KEY(id)
    );

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT AUTO_INCREMENT,
    password VARCHAR(20) NOT NULL,
    contents VARCHAR(225) NOT NULL,
    likes INT NOT NULL DEFAULT 0,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT user_PK PRIMARY KEY(id),
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
    );